/**
 * Legacy IcoMoon names, plus a few semantic aliases, mapped to solid
 * MaterialCommunityIcons glyphs shipped with react-native-vector-icons 10.2.0.
 * Outline glyphs are kept only where the UI already distinguishes
 * selected (filled) from unselected (outline).
 */
export const MDI_ICON_MAP: Record<string, string> = {
  share: 'share',
  full_stop: 'circle',
  'sd-card': 'sd',
  help: 'help-circle',
  'checkbox-blank-outline': 'checkbox-blank-outline',
  'checkbox-marked': 'checkbox-marked',
  'minus-box': 'minus-box',
  home: 'home',
  menu: 'menu',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'back-2': 'arrow-left',
  remove: 'close',
  'chevron-left-2': 'chevron-left',
  'chevron-right-2': 'chevron-right',
  slider: 'tune',
  'lyric-off': 'subtitles-outline',
  'lyric-on': 'subtitles',
  comment: 'comment',
  'playback-rate': 'play-speed',
  'volume-mute': 'volume-mute',
  'volume-off': 'volume-off',
  'volume-low': 'volume-low',
  'volume-medium': 'volume-medium',
  'volume-higt': 'volume-high',
  eraser: 'eraser',
  available_updates: 'update',
  music_time: 'timer',
  'list-loop': 'repeat',
  'list-random': 'shuffle-variant',
  'list-order': 'playlist-play',
  'single-loop': 'repeat-once',
  single: 'numeric-1-circle',
  'play-outline': 'play',
  exit2: 'logout',
  exit: 'logout',
  add_folder: 'folder-plus',
  'thumbs-up': 'thumb-up',
  'add-music': 'music-note-plus',
  'dots-vertical': 'dots-vertical',
  close: 'close',
  pause: 'pause',
  play: 'play',
  prevMusic: 'skip-previous',
  nextMusic: 'skip-next',
  setting: 'cog',
  'download-2': 'download',
  love: 'heart',
  leaderboard: 'podium',
  album: 'album',
  'search-2': 'magnify',
}

export const resolveMdiName = (name: string): string => MDI_ICON_MAP[name] ?? name
